package com.eyecode.lessons.practice;

public enum PracticeVerificationStatus {
    SUCCESS,
    SYNTAX_ERROR,
    INVALID_CONTEXT,
    MISSING_DECLARATION,
    WRONG_TYPE,
    WRONG_NAME,
    WRONG_INITIALIZER,
    MISSING_OUTPUT,
    WRONG_OUTPUT,
    MISSING_SECOND_OUTPUT,
    MISSING_ASSIGNMENT,
    WRONG_ASSIGNMENT,
    MISSING_OPERATOR,
    MISSING_COMPARISON,
    MISSING_LOGICAL_OPERATOR
}
