export type LessonDifficulty = 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
export type LessonKind = 'THEORY' | 'PRACTICE';

export type LearningRoadmapItem = { id: string; title: string; description: string };
export type LearningRoadmapSection = { id: string; title: string; description: string; items: LearningRoadmapItem[] };
export type LessonDescriptor = {
  id: string;
  title: string;
  description: string;
  categoryId: string;
  topicId: string;
  difficulty: LessonDifficulty;
  estimatedMinutes: number;
  kind: LessonKind;
  concepts: string[];
  executable: boolean;
  practiceFiles?: LessonFile[];
};
export type LearningTopic = {
  id: string;
  title: string;
  description: string;
  categoryId: string;
  roadmapSections: LearningRoadmapSection[];
  lessons: LessonDescriptor[];
};
export type LearningCategory = { id: string; title: string; description: string; topics: LearningTopic[] };
export type LessonsCatalog = { categories: LearningCategory[] };
export type LessonEditorRange = { startLineNumber: number; startColumn: number; endLineNumber: number; endColumn: number };
export type LessonFile = { id: string; name: string; language: string; starterCode: string; readOnly: boolean; editableRange?: LessonEditorRange };
export type LessonWorkspace = { files: LessonFile[]; entryFileId: string; mainClass: string };
export type LessonPractice = { id: string; instruction: LessonInlineContent[]; files: LessonFile[]; entryFileId: string };
export type PracticeVerificationStatus = 'SUCCESS' | 'SYNTAX_ERROR' | 'INVALID_CONTEXT' | 'MISSING_DECLARATION' | 'WRONG_TYPE' | 'WRONG_NAME' | 'WRONG_INITIALIZER' | 'MISSING_OUTPUT' | 'WRONG_OUTPUT' | 'MISSING_SECOND_OUTPUT';
export type PracticeVerificationResult = { status: PracticeVerificationStatus; message: string };
export type LessonEditorCommand = {
  type: 'HIGHLIGHT_RANGE' | 'REVEAL_RANGE' | 'CLEAR_HIGHLIGHTS';
  range?: LessonEditorRange;
};
export type PresentationOperation = {
  type: 'TYPE_TEXT' | 'DELETE_TEXT' | 'REPLACE_TEXT' | 'MATERIALIZE';
  startOffset: number;
  endOffset: number;
  prefix: string;
  text: string;
  suffix: string;
};
export type PresentationProgram = { sourceCode: string; targetCode: string; operations: PresentationOperation[] };
export type LessonNavigationDirection = 'NONE' | 'FORWARD' | 'BACKWARD';
export type LessonInlineContent = { type: 'TEXT' | 'CODE' | 'EMPHASIS' | 'STRONG' | 'LINK'; text: string; url?: string };
export type LessonContentBlock = { type: 'HEADING' | 'PARAGRAPH' | 'CODE' | 'LIST' | 'CALLOUT'; text?: string; title?: string; language?: string; code?: string; items?: string[]; inlineContent?: LessonInlineContent[]; ordered?: boolean };
export type LessonAnnotation = { title: string; message: string; range: LessonEditorRange };
export type LessonSession = {
  sessionId: string;
  lessonId: string;
  kind: LessonKind;
  currentStep: number;
  currentPresentation: number;
  presentationId: string;
  canonicalCode?: string;
  presentationProgram?: PresentationProgram;
  navigationDirection: LessonNavigationDirection;
  totalSteps: number;
  state: 'ACTIVE' | 'CLOSED';
  phase: 'PRESENTATION' | 'PRACTICE' | 'COMPLETED';
  practiceCompleted: boolean;
  workspace?: LessonWorkspace;
  practice?: LessonPractice;
  title: string;
  message: string;
  contentBlocks: LessonContentBlock[];
  annotation?: LessonAnnotation;
  canPrevious: boolean;
  canNext: boolean;
  commands: LessonEditorCommand[];
};
export type LessonVerificationResponse = { verification: PracticeVerificationResult; session: LessonSession };
